name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: Install
        run: yarn

      - name: Test
        run: yarn test
